### ISSUE TITLE
how works

### ISSUE THREAD

**Issue by iecxiv** [divakarmanivel/blacktie.js#3]
how works hammenu? it is posible to click a link and open independent html into container. or i have to clone index html?

**Comment by iecxiv** [comment]
Im testing, 
var rating = demo.createStarCard("Blacktie" ,"./images/logo.png" ,5);
demo.addElement(rating);
Works perfectly.
otherwise,
var url = "./home.html";
demo.openPage(url);
Is not working. Any idea?

**Comment by divakarmanivel** [comment]
You can clone and test with existing repo first and then make edits in local. You will need to setup local server to load html pages like 'Web Server for Chrome' or host the files in a live server to not see CORS errors.
