### ISSUE TITLE
menu issue on back button in chrome

### ISSUE THREAD

**Issue by iecxiv** [divakarmanivel/blacktie.js#4]
## Expected Behavior

I want to appear closed menu when go to a menu page and go back.

## Current Behavior

When press on menu, then on a menu entry and go back with Chrome menu behaviour is unexpected.

## Possible Solution

I don´t get explanation.

## Steps to Reproduce (for bugs)

https://www.tetsiapp.com

1. Look at https://www.tetsiapp.com
2. Then click on menu, top left corner.
3. Then click on "Tetsis".
4. Go back with Chrome, and look menu behaviour.

## Context

I want, press back, and load page good.

## Your Environment

* Version used:
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop
* Link to your project: https://github.com/iecxiv/tetsiapp

**Comment by iecxiv** [comment]
I think i can make all app in one only index.html, but i have a problem. If load content from menu, menu dont get closed. Is any method for open/close menu from blacktie.js? Script based as demo.x...

**Comment by divakarmanivel** [comment]
I am able to reproduce this error. Ill try to push a fix for this.

**Comment by divakarmanivel** [comment]
I have provided a fix for this issue. Please pull latest code from master to get the updates. Thanks for supporting blacktie.js!
